// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend-go/internal/handler"
	"backend-go/internal/repository"
	"backend-go/internal/server"
	"backend-go/internal/service"
	"backend-go/pkg/app"
	"backend-go/pkg/aws"
	"backend-go/pkg/jwt"
	"backend-go/pkg/log"
	"backend-go/pkg/server/http"
	"backend-go/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	pitaya := server.NewPitaya(logger, viperViper)
	handlerHandler := handler.NewHandler(logger, pitaya)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	friendRepository := repository.NewFriendRepository(repositoryRepository)
	cloudflareR2, cleanup, err := aws.NewR2Client(viperViper)
	if err != nil {
		return nil, nil, err
	}
	userService := service.NewUserService(serviceService, userRepository, friendRepository, cloudflareR2)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	roomService := service.NewRoomService(serviceService)
	roomHandler := handler.NewRoomHandler(handlerHandler, roomService)
	messageRepository := repository.NewMessageRepository(repositoryRepository)
	messageService := service.NewMessageService(serviceService, messageRepository)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, roomHandler, userRepository, messageService, roomService)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewFriendRepository, repository.NewMessageRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRoomService, service.NewMessageService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRoomHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}

// 声明 R2 构造函数
var awsSet = wire.NewSet(aws.NewR2Client)
