services:

    mongodb:
        hostname: mongodb
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: prisma
            INIT_WAIT_SEC: 10
        ports:
            - "27017:27017"
        networks:
            - gate-tier

    nginx:
        hostname: nginx
        restart: always
        build:
            context: "./nginx"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/log:/var/log/nginx/
        ports:
            - "8081:8081"
        networks:
            - gate-tier

    backend:
        hostname: backend
        restart: always
        environment:
            DATABASE_URL: mongodb://root:prisma@mongodb:27017/test?authSource=admin&retryWrites=true&w=majority
            PORT: "8080"
        volumes:
            - ./:/usr/src/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            dockerfile: ./backend.Dockerfile
        networks:
            - gate-tier
networks:
    gate-tier:
