# version: "3.9"

services:
    mongodb:
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: prisma
            INIT_WAIT_SEC: 3
        ports: 
            - "27017:27017"
        networks:
            - gate-tier

    nginx:
        hostname: nginx
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: "./nginx"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/log:/var/log/nginx/
        ports:
            - "8081:8081"
        networks:
            - gate-tier

networks:
    gate-tier:
