// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend-go/internal/repository"
	"backend-go/internal/server"
	"backend-go/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*server.Migrate, func(), error) {
	db := repository.NewDB(viperViper, logger)
	migrate := server.NewMigrate(db, logger, viperViper)
	return migrate, func() {
	}, nil
}

// wire.go:

var migrationSet = wire.NewSet(repository.NewDB, server.NewMigrate)
