[[redirects]]
  from = "/api/*"
  to = "http://47.130.0.227:8080/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/chat/*"
  to = "http://47.130.0.227:8080/chat/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[build]
  command = "pnpm -F frontend run build"
  publish = "dist"