[[redirects]]
  from = "/api/*"
  to = "http://47.129.45.86/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/ws/*"
  to = "ws://47.129.45.86/ws/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/.well-known/*"
  to = "http://47.129.45.86/.well-known/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[build]
  command = "pnpm -F frontend run build"
  publish = "dist"
