[[redirects]]
  from = "/api/*"
  to = "http://18.141.225.236/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/ws/*"
  to = "http://18.141.225.236/ws/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[build]
  command = "pnpm -F frontend run build"
  publish = "dist"