name: Lighthouse Local CI
run-name: Lighthouse Local Audit on ${{ github.ref_name }} by ${{ github.actor }}
on: [push]
jobs:
  lighthouseci:
    name: Local LHCI Autorun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F frontend build
      - run: cd packages/frontend && pnpm dlx @lhci/cli@0.13.x autorun --config=./lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
